/* Domain-depth layer for AI Learning Studio.
   Keeps Module 01 frozen and enriches every lesson in Modules 02-06.
   Pedagogy: mechanism -> derivation -> implementation -> failure -> experiment -> research.
*/
(function(){
const P={
"Regression & Classification":{c:"Linear regression maps features to continuous targets; logistic regression maps logits to probabilities and decisions; regularization changes the objective.",m:"Use y=Xw+b, sigmoid(z), squared/log loss, gradients and L1/L2 penalties; distinguish logits, probabilities, thresholds and calibration.",b:"Implement leakage-safe preprocessing, fit/predict, metric calculation and probability calibration; compare against a reference.",f:"Diagnose underfit/overfit, ill-conditioning, imbalance, threshold effects, leakage and miscalibration."},
"Trees & Ensembles":{c:"Trees recursively partition feature space; bagging averages randomized learners; boosting builds an additive model sequentially.",m:"Derive Gini/entropy, weighted child impurity, split gain, bootstrap sampling and additive boosting updates.",b:"Implement a one-level split and inspect depth, leaves, feature usage and ensemble aggregation.",f:"Diagnose unstable splits, excessive depth, feature leakage, insufficient trees and boosting overfit."},
"Unsupervised Learning":{c:"Clustering, mixture models and dimensionality reduction infer structure without target labels under different assumptions.",m:"Derive K-means objective/update, mixture likelihood, EM responsibilities and PCA covariance/eigendecomposition.",b:"Implement one primitive and compare objective, assignments or reconstruction with a trusted reference.",f:"Probe scaling, initialization, local optima, degenerate covariance and arbitrary cluster labels."},
"Evaluation & Validation":{c:"Evaluation is measurement design: population, split, metric, uncertainty and error slices must be explicit.",m:"Derive confusion metrics, regression losses, cross-validation aggregation and bootstrap variability.",b:"Build leakage-safe splits, metrics, fold aggregation and slice-based error analysis.",f:"Find leakage, duplicate samples, metric mismatch, class imbalance and optimistic model selection."},
"ML Engineering Patterns":{c:"Reliable ML connects data contracts, reproducibility, artifacts and diagnostics into a traceable pipeline.",m:"Quantify dataset size, feature shape, metric variance, runtime, memory and resource budgets.",b:"Build configuration, validation, seeded training, artifact capture, evaluation and structured logging.",f:"Diagnose train/serve skew, nondeterminism, stale artifacts, schema drift and metric regressions."},
"Neural Network Foundations":{c:"Neural networks compose affine maps and nonlinearities; backpropagation computes gradients through that composition.",m:"Derive affine layers, activation derivatives, loss gradients and chain-rule tensor shapes.",b:"Implement a tiny MLP and backpropagation, then compare gradients and loss with autodiff.",f:"Diagnose vanishing/exploding gradients, saturation, initialization and backward-pass errors."},
"Convolutional Learning":{c:"Convolutions exploit locality and shared weights to build hierarchical spatial representations.",m:"Derive convolution output dimensions, parameter counts, receptive-field growth and shared-kernel gradients.",b:"Implement or verify a 2-D convolution and inspect activations and receptive fields.",f:"Diagnose padding artifacts, aliasing, excessive downsampling and augmentation leakage."},
"Sequence Models":{c:"Recurrent models carry hidden state through ordered observations; LSTM gates address some long-range optimization limits.",m:"Derive recurrent updates, parameter sharing through time, BPTT and LSTM gate equations.",b:"Implement a recurrent model and inspect hidden-state and gradient norms over sequence length.",f:"Diagnose vanishing/exploding gradients, hidden-state bottlenecks and exposure bias."},
"Transformer Foundations":{c:"Transformers combine attention, feed-forward blocks, residual paths and positional information for parallel sequence processing.",m:"Derive scaled dot-product attention, softmax, causal masking, tensor shapes and sequence-length cost.",b:"Implement single-head attention and compare fixed-tensor outputs with a reference.",f:"Diagnose mask leakage, shape errors, softmax overflow, normalization instability and quadratic cost."},
"Training Dynamics":{c:"Training trajectories are shaped by optimizer state, data order, regularization, precision and compute budget.",m:"Reason about gradients, momentum/Adam state, schedules, curvature, scaling and finite-precision error.",b:"Instrument gradients, parameter norms, learning rate, throughput and validation.",f:"Diagnose divergence, NaNs, underflow, gradient explosions and unstable mixed precision."},
"Information Retrieval":{c:"Retrieval maps queries to candidates and ranks them using lexical, vector or learned relevance signals.",m:"Derive similarity and ranking metrics such as precision@k, recall@k and nDCG.",b:"Implement candidate generation, ranking and labeled relevance evaluation.",f:"Diagnose recall misses, chunking, duplicates, reranking errors and latency."},
"Reinforcement Learning":{c:"RL learns behavior from interaction using states, actions, rewards and long-term return.",m:"Derive MDPs, discounted return, Bellman equations and policy-gradient intuition.",b:"Implement a tabular value or policy method before function approximation.",f:"Diagnose exploration failure, sparse rewards, reward hacking, unstable bootstrapping and train/eval mismatch."},
"Reasoning Systems":{c:"Reasoning systems combine search, decomposition and verification; additional computation introduces branching and correlated failure.",m:"Analyze branching factor, search depth, verification cost and accuracy/compute trade-offs.",b:"Implement bounded candidate generation, scoring and verification with explicit termination.",f:"Diagnose search explosion, correlated candidate errors and verifier reward hacking."},
"Distributed ML":{c:"Distributed ML partitions data, model computation or pipeline stages while paying communication and synchronization costs.",m:"Reason about compute/communication ratio, batch scaling, synchronization and per-device memory.",b:"Prototype data/model parallel work and instrument step, communication and memory.",f:"Diagnose stragglers, imbalance, synchronization overhead, duplicate data and inconsistent state."},
"Multimodal AI":{c:"Multimodal systems align or fuse representations from different modalities through encoders and cross-modal objectives.",m:"Reason about embedding spaces, contrastive loss, projection dimensions and cross-attention.",b:"Build a paired text/image retrieval or fusion experiment and inspect modality-specific errors.",f:"Diagnose modality imbalance, shortcut learning, misalignment and spurious correlations."},
"LLM Architecture":{c:"LLM behavior emerges from tokenization, transformer computation, context management and autoregressive decoding.",m:"Derive token-to-embedding flow, attention complexity, KV-cache memory and autoregressive probability.",b:"Trace tokens through embeddings, attention, logits and decoding; instrument cache growth.",f:"Diagnose tokenization surprises, context truncation, cache misuse and decoding artifacts."},
"Pretraining & Adaptation":{c:"Pretraining learns broad representations; supervised and parameter-efficient adaptation changes behavior with smaller objectives.",m:"Reason about next-token likelihood, token loss, parameter counts and low-rank updates.",b:"Prepare clean data and compare a small full-update run with a parameter-efficient update.",f:"Diagnose contamination, catastrophic forgetting, label noise, overfit and train/eval mismatch."},
"Post-training":{c:"Post-training shapes behavior from preference or reward signals; DPO, RLHF/RLAIF and reward modeling make different assumptions.",m:"Track preference likelihoods, KL constraints, reward scores and reference-policy relationships.",b:"Build a small preference dataset and compare direct preference optimization with a supervised baseline.",f:"Diagnose reward hacking, preference noise, overoptimization and reference divergence."},
"RAG & Tool Use":{c:"RAG and tool systems connect models to evidence or actions through retrieval, planning, execution and verification.",m:"Track retrieval recall, context budget, tool success probability, expected cost and compounded multi-step error.",b:"Implement typed retrieval/tool interfaces with validation, bounded retries, provenance and failure states.",f:"Diagnose retrieval misses, prompt injection, stale context, malformed calls and loops."},
"Agent Evaluation & Safety":{c:"Agent evaluation measures multi-step behavior while safety engineering constrains tools, privileges, state and recovery.",m:"Define task success, attack success, expected cost and uncertainty over repeated episodes.",b:"Build deterministic fixtures, adversarial inputs, permission boundaries, traces and reproducible scoring.",f:"Diagnose prompt injection, tool misuse, privilege escalation, persistence and evaluator leakage."},
"GPU & Inference Systems":{c:"GPU inference performance depends on arithmetic intensity, memory movement, launch overhead, batching, precision and serving.",m:"Estimate FLOPs, memory traffic, arithmetic intensity, throughput, latency and quantization error.",b:"Profile inference and compare batching, precision or optimized execution with end-to-end telemetry.",f:"Diagnose bandwidth limits, launch overhead, synchronization, padding waste and quality loss."},
"Cloud & MLOps":{c:"Production ML needs versioned artifacts, automated validation, deployment controls, observability and reproducible environments.",m:"Quantify latency, failure rate, resource cost, drift and artifact provenance.",b:"Build a containerized service or pipeline with CI checks, versioned artifacts, health checks and metrics.",f:"Diagnose dependency drift, bad artifacts, rollback failure, schema changes and missing telemetry."},
"Performance Engineering":{c:"Performance engineering identifies the limiting resource, changes it and verifies the end-to-end effect.",m:"Use throughput, latency percentiles, utilization, memory bandwidth and Amdahl-style reasoning.",b:"Instrument CPU/GPU, memory, I/O and request latency with a reproducible benchmark.",f:"Diagnose warm-up noise, contention, serialization, cache effects and non-bottleneck optimization."},
"Research Engineering":{c:"Research engineering converts hypotheses into reproducible experiments with baselines, ablations and negative results.",m:"Track effect sizes, variance, uncertainty, compute budget and experimental degrees of freedom.",b:"Build an experiment runner with configs, seeds, artifacts, checkpoints, metrics and manifests.",f:"Diagnose selective reporting, incomparable baselines, hidden preprocessing and missing seeds."},
"Portfolio & Interview Engineering":{c:"Technical demonstration is evidence: architecture, implementation, tests, benchmarks, debugging records and trade-offs must be reconstructable.",m:"Quantify complexity, latency, memory, accuracy, cost and constraints.",b:"Turn an artifact into a reproducible project with architecture, tests, benchmark and failure log.",f:"Diagnose weak baselines, demo-only success, untested assumptions and unexplained trade-offs."}
};
const steps={
Foundation:u=>["Identify the objects, assumptions and observable behavior in "+u+".","Predict one measurable outcome before using an abstraction.","State a boundary where the method should not be trusted."],
Derivation:u=>["Write the governing relationship for "+u+" and define every symbol.","Derive it step by step and verify numerically.","State the validity assumption and construct a counterexample if violated."],
Implementation:u=>["Build the smallest correct implementation.","Test normal, boundary and adversarial cases against a reference.","Record an invariant that must survive refactoring."],
Engineering:u=>["Reproduce a realistic failure.","Instrument the relevant metric/resource/invariant and isolate the smallest failing case.","Fix the root cause and add a regression test."],
Experiment:u=>["Predeclare a hypothesis and primary metric.","Change one meaningful factor and repeat the measurement.","Separate observation, interpretation, uncertainty and limitation."],
Research:u=>["Frame a falsifiable question with a meaningful baseline.","Define what result would disconfirm it and run the protocol.","Report negative results, threats to validity and the next experiment."]
};
const kind=["baseline transfer","edge-case transfer","scale transfer","ablation transfer","adversarial transfer","systems transfer","research transfer"];
for(const l of window.LESSONS||[]){
 if(l.module==="m1") continue;
 const p=P[l.unit]; if(!p) throw new Error("No depth profile for "+l.unit);
 const st=steps[l.stage](l.unit);
 l.lessonBody=p.c+" The learner must preserve the mechanism while changing one controlled condition ("+kind[l.order%kind.length]+").";
 l.mentalModel=[p.c,"Trace input → transformation → state → output → measurement.","Treat assumptions and failure boundaries as first-class model components."];
 l.vocabulary=[l.unit,"assumption","invariant","failure boundary","baseline","evidence"];
 l.math=p.m+" "+(l.stage==="Derivation"?"Map every symbol to the implementation and verify the algebra numerically.":"State which quantities are observed, optimized or constrained.");
 l.mechanism=p.c+" Trace the mechanism as input → transformation → intermediate state → output → measurement.";
 l.implementation=p.b+" Add assertions, a trusted-reference comparison and an adversarial case.";
 l.experiment=p.c+" Change one meaningful factor, freeze the baseline, repeat measurements and preserve raw results.";
 l.failure=p.f+" Root-cause sequence: reproduce → instrument → isolate → test alternatives → fix → regression test.";
 l.research="Form a falsifiable question about "+l.unit+", define a baseline and a disconfirming result, then report uncertainty, negative results and threats to validity.";
 l.stageSteps=st;
 l.workedExample={title:l.stage+" worked example — "+l.unit,text:p.c,steps:st};
 l.secondExample={title:"Failure-boundary example — "+l.unit,text:p.f,steps:["Freeze the baseline.","Change one relevant condition.","Predict the boundary behavior.","Measure and explain the result."]};
 l.practice=["Reconstruct the mechanism without copying the example.","Apply it to a new dataset, configuration or constraint.","Add a boundary/adversarial test.","Compare against baseline evidence.","Explain what remained invariant and what changed."];
 l.beginnerWarnings=["Do not hide assumptions behind defaults.","Do not change multiple variables when testing causality.","Do not treat one run as a stable result.","A passing demo is not proof of correctness."];
 l.lab={title:l.unit+" — "+l.stage+" deep lab",objective:"Build, break and measure the mechanism under a controlled change.",steps:["Create a reproducible baseline.","Apply the stage-specific intervention.","Capture measurements and failure traces.","Explain the result and limitation."],success:"Reproducible artifact, explicit invariant and evidence-backed conclusion."};
 l.misconceptions=["API usage is not the same as understanding.","A better aggregate metric does not prove every failure mode improved.","A surprising result must be investigated before being labeled a bug.","Changing assumptions can change the valid operating regime."];
 l.checkpoint=["What is the central mechanism or invariant?","What controlled change exposes its boundary?","What evidence would convince another engineer?"];
 l.checkpointAnswers=[p.c,p.f,"A reproducible baseline comparison with explicit measurements, assumptions and limitations."];
 l.highlights=[l.unit+" — mechanism before optimization.","Baseline → intervention → measurement → interpretation.","Failure boundaries are part of the concept.","Reproducibility is evidence."];
 l.keyNotes=["Define objects and assumptions before implementation.","Keep the evaluation protocol fixed while changing the intended variable.","Preserve unsuccessful runs.","Connect the lesson to the next stage."];
 l.evidence="Evidence must demonstrate the mechanism, controlled implementation or derivation, measured behavior, failure analysis and limitations.";
 l.deliverable="Submit the artifact, tests, baseline comparison, failure analysis and concise technical note.";
}
window.__CURRICULUM_DEPTH_AUDIT={profiles:Object.keys(P).length,enriched:window.LESSONS.filter(l=>l.module!=="m1").length};
})();