/* Domain-depth layer for AI Learning Studio.
   Keeps Module 01 frozen and enriches every lesson in Modules 02-06.
   Pedagogy: mechanism -> derivation -> implementation -> failure -> experiment -> research.
*/
(function(){
const P={
"Regression & Classification":{c:"Linear regression maps features to continuous targets; logistic regression maps logits to probabilities and decisions; regularization changes the objective.",m:"Use y=Xw+b, sigmoid(z), squared/log loss, gradients and L1/L2 penalties; distinguish logits, probabilities, thresholds and calibration.",b:"Implement leakage-safe preprocessing, fit/predict, metric calculation and probability calibration; compare against a reference.",f:"Diagnose underfit/overfit, ill-conditioning, imbalance, threshold effects, leakage and miscalibration."},
"Trees & Ensembles":{c:"Trees recursively partition feature space; bagging averages randomized learners; boosting builds an additive model sequentially.",m:"Derive Gini/entropy, weighted child impurity, split gain, bootstrap sampling and additive boosting updates.",b:"Implement a one-level split and inspect depth, leaves, feature usage and ensemble aggregation.",f:"Diagnose unstable splits, excessive depth, feature leakage, insufficient trees and boosting overfit."},
"Unsupervised Learning":{c:"Clustering, mixture models and dimensionality reduction infer structure without target labels under different assumptions.",m:"Derive K-means objective/update, mixture likelihood, EM responsibilities and PCA covariance/eigendecomposition.",b:"Implement one primitive and compare objective, assignments or reconstruction with a trusted reference.",f:"Probe scaling, initialization, local optima, degenerate covariance and arbitrary cluster labels."},
"Evaluation & Validation":{c:"Evaluation is measurement design: population, split, metric, uncertainty and error slices must be explicit.",m:"Derive confusion metrics, regression losses, cross-validation aggregation and bootstrap variability.",b:"Build leakage-safe splits, metrics, fold aggregation and slice-based error analysis.",f:"Find leakage, duplicate samples, metric mismatch, class imbalance and optimistic model selection."},
"ML Engineering Patterns":{c:"Reliable ML connects data contracts, reproducibility, artifacts and diagnostics into a traceable pipeline.",m:"Quantify dataset size, feature shape, metric variance, runtime, memory and resource budgets.",b:"Build configuration, validation, seeded training, artifact capture, evaluation and structured logging.",f:"Diagnose train/serve skew, nondeterminism, stale artifacts, schema drift and metric regressions."},
"Neural Network Foundations":{c:"Neural networks compose affine maps and nonlinearities; backpropagation computes gradients through that composition.",m:"Derive affine layers, activation derivatives, loss gradients and chain-rule tensor shapes.",b:"Implement a tiny MLP and backpropagation, then compare gradients and loss with autodiff.",f:"Diagnose vanishing/exploding gradients, saturation, initialization and backward-pass errors."},
"Convolutional Learning":{c:"Convolutions exploit locality and shared weights to build hierarchical spatial representations.",m:"Derive convolution output dimensions, parameter counts, receptive-field growth and shared-kernel gradients.",b:"Implement or verify a 2-D convolution and inspect activations and receptive fields.",f:"Diagnose padding artifacts, aliasing, excessive downsampling and augmentation leakage."},
"Sequence Models":{c:"Recurrent models carry hidden state through ordered observations; LSTM gates address some long-range optimization limits.",m:"Derive recurrent updates, parameter sharing through time, BPTT and LSTM gate equations.",b:"Implement a recurrent model and inspect hidden-state and gradient norms over sequence length.",f:"Diagnose vanishing/exploding gradients, hidden-state bottlenecks and exposure bias."},
"Transformer Foundations":{c:"Transformers combine attention, feed-forward blocks, residual paths and positional information for parallel sequence processing.",m:"Derive scaled dot-product attention, softmax, causal masking, tensor shapes and sequence-length cost.",b:"Implement single-head attention and compare fixed-tensor outputs with a reference.",f:"Diagnose mask leakage, shape errors, softmax overflow, normalization instability and quadratic cost."},
"Training Dynamics":{c:"Training trajectories are shaped by optimizer state, data order, regularization, precision and compute budget.",m:"Reason about gradients, momentum/Adam state, schedules, curvature, scaling and finite-precision error.",b:"Instrument gradients, parameter norms, learning rate, throughput and validation.",f:"Diagnose divergence, NaNs, underflow, gradient explosions and unstable mixed precision."},
"Information Retrieval":{c:"Retrieval maps queries to candidates and ranks them using lexical, vector or learned relevance signals.",m:"Derive similarity and ranking metrics such as precision@k, recall@k and nDCG.",b:"Implement candidate generation, ranking and labeled relevance evaluation.",f:"Diagnose recall misses, chunking, duplicates, reranking errors and latency."},
"Reinforcement Learning":{c:"RL learns behavior from interaction using states, actions, rewards and long-term return.",m:"Derive MDPs, discounted return, Bellman equations and policy-gradient intuition.",b:"Implement a tabular value or policy method before function approximation.",f:"Diagnose exploration failure, sparse rewards, reward hacking, unstable bootstrapping and train/eval mismatch."},
"Reasoning Systems":{c:"Reasoning systems combine search, decomposition and verification; additional computation introduces branching and correlated failure.",m:"Analyze branching factor, search depth, verification cost and accuracy/compute trade-offs.",b:"Implement bounded candidate generation, scoring and verification with explicit termination.",f:"Diagnose search explosion, correlated candidate errors and verifier reward hacking."},
"Distributed ML":{c:"Distributed ML partitions data, model computation or pipeline stages while paying communication and synchronization costs.",m:"Reason about compute/communication ratio, batch scaling, synchronization and per-device memory.",b:"Prototype data/model parallel work and instrument step, communication and memory.",f:"Diagnose stragglers, imbalance, synchronization overhead, duplicate data and inconsistent state."},
"Multimodal AI":{c:"Multimodal systems align or fuse representations from different modalities through encoders and cross-modal objectives.",m:"Reason about embedding spaces, contrastive loss, projection dimensions and cross-attention.",b:"Build a paired text/image retrieval or fusion experiment and inspect modality-specific errors.",f:"Diagnose modality imbalance, shortcut learning, misalignment and spurious correlations."},
"LLM Architecture":{c:"LLM behavior emerges from tokenization, transformer computation, context management and autoregressive decoding.",m:"Derive token-to-embedding flow, attention complexity, KV-cache memory and autoregressive probability.",b:"Trace tokens through embeddings, attention, logits and decoding; instrument cache growth.",f:"Diagnose tokenization surprises, context truncation, cache misuse and decoding artifacts."},
"Pretraining & Adaptation":{c:"Pretraining learns broad representations; supervised and parameter-efficient adaptation changes behavior with smaller objectives.",m:"Reason about next-token likelihood, token loss, parameter counts and low-rank updates.",b:"Prepare clean data and compare a small full-update run with a parameter-efficient update.",f:"Diagnose contamination, catastrophic forgetting, label noise, overfit and train/eval mismatch."},
"Post-training":{c:"Post-training shapes behavior from preference or reward signals; DPO, RLHF/RLAIF and reward modeling make different assumptions.",m:"Track preference likelihoods, KL constraints, reward scores and reference-policy relationships.",b:"Build a small preference dataset and compare direct preference optimization with a supervised baseline.",f:"Diagnose reward hacking, preference noise, overoptimization and reference divergence."},
"RAG & Tool Use":{c:"RAG and tool systems connect models to evidence or actions through retrieval, planning, execution and verification.",m:"Track retrieval recall, context budget, tool success probability, expected cost and compounded multi-step error.",b:"Implement typed retrieval/tool interfaces with validation, bounded retries, provenance and failure states.",f:"Diagnose retrieval misses, prompt injection, stale context, malformed calls and loops."},
"Agent Evaluation & Safety":{c:"Agent evaluation measures multi-step behavior while safety engineering constrains tools, privileges, state and recovery.",m:"Define task success, attack success, expected cost and uncertainty over repeated episodes.",b:"Build deterministic fixtures, adversarial inputs, permission boundaries, traces and reproducible scoring.",f:"Diagnose prompt injection, tool misuse, privilege escalation, persistence and evaluator leakage."},
"GPU & Inference Systems":{c:"GPU inference performance depends on arithmetic intensity, memory movement, launch overhead, batching, precision and serving.",m:"Estimate FLOPs, memory traffic, arithmetic intensity, throughput, latency and quantization error.",b:"Profile inference and compare batching, precision or optimized execution with end-to-end telemetry.",f:"Diagnose bandwidth limits, launch overhead, synchronization, padding waste and quality loss."},
"Cloud & MLOps":{c:"Production ML needs versioned artifacts, automated validation, deployment controls, observability and reproducible environments.",m:"Quantify latency, failure rate, resource cost, drift and artifact provenance.",b:"Build a containerized service or pipeline with CI checks, versioned artifacts, health checks and metrics.",f:"Diagnose dependency drift, bad artifacts, rollback failure, schema changes and missing telemetry."},
"Performance Engineering":{c:"Performance engineering identifies the limiting resource, changes it and verifies the end-to-end effect.",m:"Use throughput, latency percentiles, utilization, memory bandwidth and Amdahl-style reasoning.",b:"Instrument CPU/GPU, memory, I/O and request latency with a reproducible benchmark.",f:"Diagnose warm-up noise, contention, serialization, cache effects and non-bottleneck optimization."},
"Research Engineering":{c:"Research engineering converts hypotheses into reproducible experiments with baselines, ablations and negative results.",m:"Track effect sizes, variance, uncertainty, compute budget and experimental degrees of freedom.",b:"Build an experiment runner with configs, seeds, artifacts, checkpoints, metrics and manifests.",f:"Diagnose selective reporting, incomparable baselines, hidden preprocessing and missing seeds."},
"Portfolio & Interview Engineering":{c:"Technical demonstration is evidence: architecture, implementation, tests, benchmarks, debugging records and trade-offs must be reconstructable.",m:"Quantify complexity, latency, memory, accuracy, cost and constraints.",b:"Turn an artifact into a reproducible project with architecture, tests, benchmark and failure log.",f:"Diagnose weak baselines, demo-only success, untested assumptions and unexplained trade-offs."}
};
const steps={
Foundation:u=>["Identify the objects, assumptions and observable behavior in "+u+".","Predict one measurable outcome before using an abstraction.","State a boundary where the method should not be trusted."],
Derivation:u=>["Write the governing relationship for "+u+" and define every symbol.","Derive it step by step and verify numerically.","State the validity assumption and construct a counterexample if violated."],
Implementation:u=>["Build the smallest correct implementation.","Test normal, boundary and adversarial cases against a reference.","Record an invariant that must survive refactoring."],
Engineering:u=>["Reproduce a realistic failure.","Instrument the relevant metric/resource/invariant and isolate the smallest failing case.","Fix the root cause and add a regression test."],
Experiment:u=>["Predeclare a hypothesis and primary metric.","Change one meaningful factor and repeat the measurement.","Separate observation, interpretation, uncertainty and limitation."],
Research:u=>["Frame a falsifiable question with a meaningful baseline.","Define what result would disconfirm it and run the protocol.","Report negative results, threats to validity and the next experiment."]
};

// Applied AI Tools catalog — current ecosystem, taught as tool fluency rather than vendor memorization.
// Each tool is tied to a concrete workflow, verification habit and failure mode.
const AI_TOOLS=[
 {id:"chatgpt",name:"ChatGPT",category:"General AI / Work",skills:["prompting","deep research","files","workflows","coding"],mission:"Turn a vague task into a verified research-to-deliverable workflow; compare the model's claims against primary sources."},
 {id:"claude",name:"Claude",category:"General AI / Coding",skills:["reasoning","long-context analysis","coding","artifacts"],mission:"Use a long-context model to analyze a multi-file technical problem and produce a traceable implementation plan."},
 {id:"gemini",name:"Gemini",category:"General AI / Multimodal",skills:["multimodal","tool use","function calling","grounded workflows"],mission:"Build a tool-calling workflow and verify every returned argument before execution."},
 {id:"perplexity",name:"Perplexity",category:"AI Search / Research",skills:["web research","citations","source comparison"],mission:"Answer a research question using visible sources, then replace secondary claims with primary evidence."},
 {id:"notebooklm",name:"NotebookLM",category:"Research / Learning",skills:["source-grounded synthesis","study guides","audio summaries"],mission:"Create a source-grounded study brief and identify which claims are actually supported by the uploaded corpus."},
 {id:"github-copilot",name:"GitHub Copilot",category:"Coding",skills:["code completion","review","tests","repository context"],mission:"Generate an implementation only after writing the contract and tests; review every generated change."},
 {id:"cursor",name:"Cursor",category:"Coding Agent / IDE",skills:["codebase reasoning","agent edits","debugging","refactoring"],mission:"Give an agent a bounded repository task, inspect its diff, run tests and reject unsupported changes."},
 {id:"codex",name:"OpenAI Codex",category:"Coding Agent",skills:["end-to-end coding","testing","review","automation"],mission:"Delegate a real engineering task with acceptance criteria, then verify the resulting code and tests."},
 {id:"claude-code",name:"Claude Code",category:"Coding Agent / Terminal",skills:["terminal agents","codebase tasks","automation"],mission:"Run a constrained terminal coding workflow with explicit permissions and regression checks."},
 {id:"vscode-ai",name:"VS Code AI workflows",category:"Developer Tooling",skills:["editor agents","debugging","extensions"],mission:"Combine editor assistance with tests and static analysis instead of accepting generated code blindly."},
 {id:"hugging-face",name:"Hugging Face",category:"Models / Open Source",skills:["model discovery","datasets","transformers","spaces"],mission:"Select an open model from its card, inspect license and evaluation evidence, then run a reproducible inference test."},
 {id:"ollama",name:"Ollama",category:"Local AI",skills:["local inference","model management","privacy"],mission:"Run a local model, measure latency and memory, and compare its behavior with a hosted baseline."},
 {id:"lm-studio",name:"LM Studio",category:"Local AI",skills:["local models","API serving","experimentation"],mission:"Serve a local model through an API and measure throughput, latency and context behavior."},
 {id:"open-webui",name:"Open WebUI",category:"Local AI / Interface",skills:["local assistants","RAG","model routing"],mission:"Configure a local AI interface and document model, retrieval and permission boundaries."},
 {id:"langgraph",name:"LangGraph",category:"Agent Framework",skills:["state machines","agent graphs","durable workflows"],mission:"Build a bounded stateful agent graph with explicit transitions, retries and termination."},
 {id:"openai-agents-sdk",name:"OpenAI Agents SDK",category:"Agent Framework",skills:["agents","tools","handoffs","tracing"],mission:"Build an agent with typed tools and inspect the trace before trusting the final result."},
 {id:"pydantic-ai",name:"PydanticAI",category:"Agent Framework",skills:["typed agents","structured outputs","validation"],mission:"Create a typed agent interface where invalid tool arguments fail safely."},
 {id:"mcp",name:"Model Context Protocol (MCP)",category:"Tool Connectivity",skills:["tool servers","resources","permissions","context"],mission:"Connect a model to a narrowly scoped tool server and audit the permissions exposed."},
 {id:"langfuse",name:"Langfuse",category:"LLM Observability",skills:["tracing","cost","latency","evaluation"],mission:"Trace an LLM workflow and identify the exact step responsible for quality or latency regression."},
 {id:"arize-phoenix",name:"Arize Phoenix",category:"AI Observability",skills:["tracing","evaluations","RAG debugging"],mission:"Inspect traces and evaluate retrieval and generation separately."},
 {id:"promptfoo",name:"Promptfoo",category:"AI Evaluation",skills:["evals","red teaming","regression tests"],mission:"Create a prompt regression suite with adversarial cases and measurable pass/fail criteria."},
 {id:"qdrant",name:"Qdrant",category:"Vector Search",skills:["embeddings","vector retrieval","filters"],mission:"Build a small semantic retrieval index and evaluate recall before adding a generator."},
 {id:"pgvector",name:"pgvector",category:"Vector Database",skills:["SQL","embeddings","hybrid retrieval"],mission:"Implement vector search inside PostgreSQL and compare retrieval quality with a simple lexical baseline."},
 {id:"pinecone",name:"Pinecone",category:"Vector Infrastructure",skills:["managed vector search","metadata filters","retrieval"],mission:"Design a production-style vector retrieval schema and measure recall/latency trade-offs."},
 {id:"weaviate",name:"Weaviate",category:"Vector Database",skills:["vector search","hybrid search","metadata"],mission:"Compare semantic and hybrid retrieval on a labeled query set."},
 {id:"firecrawl",name:"Firecrawl",category:"Web Data / RAG",skills:["web extraction","crawl","structured content"],mission:"Create a reproducible web-ingestion pipeline and validate source freshness and provenance."},
 {id:"v0",name:"v0",category:"AI UI / Prototyping",skills:["UI generation","React","rapid prototyping"],mission:"Generate a UI prototype, then convert the visual result into explicit accessibility and component requirements."},
 {id:"lovable",name:"Lovable",category:"AI App Builder",skills:["rapid app generation","full-stack prototypes"],mission:"Build a small app from a specification and audit generated architecture, dependencies and security."},
 {id:"replit-agent",name:"Replit Agent",category:"AI App Builder",skills:["app generation","deployment","debugging"],mission:"Generate a working prototype, inspect the implementation and reproduce it locally."},
 {id:"bolt",name:"Bolt",category:"AI App Builder",skills:["web generation","prototyping","iteration"],mission:"Turn a product brief into a prototype and test the generated interaction paths."},
 {id:"canva-ai",name:"Canva AI",category:"Design / Content",skills:["visual generation","presentations","brand workflows"],mission:"Create a visual asset from a structured brief and verify hierarchy, consistency and factual copy."},
 {id:"figma-ai",name:"Figma AI",category:"Design / Product",skills:["UI generation","design systems","prototyping"],mission:"Generate a UI direction, then translate it into reusable components and design tokens."},
 {id:"midjourney",name:"Midjourney",category:"Image Generation",skills:["visual ideation","style control","composition"],mission:"Iterate a visual prompt while documenting which variables changed and evaluating consistency."},
 {id:"runway",name:"Runway",category:"Video Generation",skills:["video generation","editing","visual workflows"],mission:"Produce a short visual sequence and evaluate temporal consistency and prompt adherence."},
 {id:"elevenlabs",name:"ElevenLabs",category:"Voice / Audio",skills:["speech generation","voice workflows","audio"],mission:"Create a narrated learning artifact and evaluate pronunciation, pacing and factual alignment."},
 {id:"suno",name:"Suno",category:"Music Generation",skills:["music generation","creative workflows"],mission:"Generate music from a structured brief and evaluate adherence to constraints."},
 {id:"descript",name:"Descript",category:"AI Media Editing",skills:["transcription","editing","voice"],mission:"Transform a transcript into an edited instructional clip while checking every generated edit."},
 {id:"zapier-ai",name:"Zapier AI",category:"Automation",skills:["workflow automation","connectors","actions"],mission:"Automate a multi-step task with explicit triggers, permissions, retries and failure handling."},
 {id:"make-ai",name:"Make",category:"Automation",skills:["workflow orchestration","APIs","automation"],mission:"Build a visual automation and identify every state transition and failure path."},
 {id:"n8n",name:"n8n",category:"Automation / Self-hosted",skills:["workflow automation","webhooks","agents"],mission:"Create a self-hosted AI workflow with secrets isolation and deterministic error handling."},
 {id:"aws-bedrock",name:"Amazon Bedrock",category:"Model Platform",skills:["model APIs","agents","guardrails","RAG"],mission:"Compare model invocation and tool/RAG patterns behind a provider-neutral interface."},
 {id:"azure-ai",name:"Azure AI",category:"Model Platform",skills:["enterprise AI","model deployment","evaluation"],mission:"Design an enterprise AI workflow with identity, logging and evaluation boundaries."},
 {id:"google-ai-studio",name:"Google AI Studio",category:"Model Prototyping",skills:["Gemini","prompting","tool use"],mission:"Prototype a multimodal tool workflow and inspect function-call arguments before execution."},
 {id:"vertex-ai",name:"Vertex AI",category:"ML Platform",skills:["model development","evaluation","deployment"],mission:"Design a model lifecycle from experiment to monitored endpoint with explicit artifact lineage."},
 {id:"weights-biases",name:"Weights & Biases",category:"ML Experimentation",skills:["experiment tracking","artifacts","sweeps"],mission:"Track an experiment family and prove which configuration produced the reported result."}
];
globalThis.AI_TOOLS=AI_TOOLS;
const kind=["baseline transfer","edge-case transfer","scale transfer","ablation transfer","adversarial transfer","systems transfer","research transfer"];
const CONCEPTS={
"Regression & Classification":["Linear regression geometry","Loss functions and residuals","Logistic logits and probabilities","Regularization and feature scaling","Decision thresholds","Calibration","Imbalance and class-weighted learning"],
"Trees & Ensembles":["Recursive partitioning","Gini and entropy","Pruning and depth","Bootstrap aggregation","Random feature selection","Boosting residuals","Feature importance and leakage"],
"Unsupervised Learning":["K-means geometry","Initialization and local minima","Gaussian mixtures","EM responsibilities","PCA covariance","Dimensionality reduction","Cluster validation"],
"Evaluation & Validation":["Train/validation/test roles","Metric selection","Confusion-matrix analysis","Cross-validation","Bootstrap uncertainty","Leakage detection","Slice and error analysis"],
"ML Engineering Patterns":["Data contracts","Reproducible configuration","Feature pipelines","Artifact lineage","Experiment tracking","Train/serve parity","Drift and regression monitoring"],
"Neural Network Foundations":["Affine layers","Activation functions","Loss gradients","Chain rule","Backpropagation","Initialization","Gradient diagnostics"],
"Convolutional Learning":["Kernel geometry","Padding and stride","Receptive fields","Parameter sharing","Normalization","Augmentation","Visual error analysis"],
"Sequence Models":["Hidden state","BPTT","Vanishing gradients","LSTM gates","Teacher forcing","Sequence batching","Exposure bias"],
"Transformer Foundations":["Q/K/V projections","Scaled dot-product attention","Causal masking","Multi-head attention","Residual paths","Normalization","Attention complexity"],
"Training Dynamics":["SGD dynamics","Momentum","Adam state","Learning-rate schedules","Regularization","Mixed precision","NaN and divergence diagnosis"],
"Information Retrieval":["Inverted indexes","Dense embeddings","Similarity search","Candidate recall","Ranking functions","nDCG and recall@k","Reranking and latency"],
"Reinforcement Learning":["MDP formulation","Bellman equations","TD learning","Q-learning","Policy gradients","Exploration","Reward design"],
"Reasoning Systems":["Search trees","Candidate sampling","Self-consistency","Verifiers","Compute budgets","Termination","Reasoning evaluation"],
"Distributed ML":["Data parallelism","Gradient synchronization","Tensor parallelism","Pipeline parallelism","Communication overlap","Stragglers","Distributed checkpointing"],
"Multimodal AI":["Modality encoders","Projection spaces","Contrastive alignment","Cross-attention","Fusion strategies","Modality imbalance","Shortcut detection"],
"LLM Architecture":["Tokenization","Embeddings","Self-attention","Position information","KV cache","Context windows","Autoregressive decoding"],
"Pretraining & Adaptation":["Data mixture design","Next-token objective","Contamination controls","SFT","PEFT and LoRA","Catastrophic forgetting","Adaptation evaluation"],
"Post-training":["Preference datasets","Reward modeling","RLHF","RLAIF","DPO","KL/reference policy","Reward hacking"],
"RAG & Tool Use":["Chunking","Embedding retrieval","Reranking","Context assembly","Typed tools","Provenance","Bounded execution"],
"Agent Evaluation & Safety":["Task success metrics","Episode traces","Prompt injection","Privilege boundaries","Tool misuse","Adversarial evaluation","Sandbox recovery"],
"GPU & Inference Systems":["GPU execution model","Kernel launch overhead","Memory bandwidth","Arithmetic intensity","Quantization","Batching","Serving latency"],
"Cloud & MLOps":["Containerization","CI validation","Artifact registries","Deployment strategies","Observability","Reproducibility","Rollback and drift"],
"Performance Engineering":["Profiling","Latency percentiles","Throughput","Memory behavior","I/O bottlenecks","Amdahl reasoning","Benchmark hygiene"],
"Research Engineering":["Hypothesis design","Baselines","Ablations","Seeds and variance","Experiment manifests","Negative results","Technical reporting"],
"Portfolio & Interview Engineering":["System architecture","Complexity analysis","Testing","Benchmarking","Failure narratives","Trade-off reasoning","Reproducible demonstration"]
};
const conceptState={};

for(const l of LESSONS||[]){
 if(l.module==="m1") continue;
 const p=P[l.unit]; if(!p) throw new Error("No depth profile for "+l.unit);
 const st=steps[l.stage](l.unit);
 const conceptList=CONCEPTS[l.unit]; if(!conceptList) throw new Error("No concept map for "+l.unit);
 const conceptIndex=conceptState[l.unit]||0;
 const concept=conceptList[conceptIndex%conceptList.length];
 conceptState[l.unit]=conceptIndex+1;
 l.title=l.stage+" · "+concept;
 l.lessonBody="Concept focus: "+concept+". "+p.c+" The learner must preserve the mechanism while changing one controlled condition ("+kind[l.order%kind.length]+").";
 l.mentalModel=[p.c,"Trace input → transformation → state → output → measurement.","Treat assumptions and failure boundaries as first-class model components."];
 l.vocabulary=[l.unit,"assumption","invariant","failure boundary","baseline","evidence"];
 l.math="Concept: "+concept+". "+p.m+" "+(l.stage==="Derivation"?"Map every symbol to the implementation and verify the algebra numerically.":"State which quantities are observed, optimized or constrained.");
 l.mechanism="Focus on "+concept+": "+p.c+" Trace the mechanism as input → transformation → intermediate state → output → measurement.";
 l.implementation="Implement "+concept+". "+p.b+" Add assertions, a trusted-reference comparison and an adversarial case.";
 l.experiment="Experiment on "+concept+". "+p.c+" Change one meaningful factor, freeze the baseline, repeat measurements and preserve raw results.";
 l.failure="Failure analysis for "+concept+": "+p.f+" Root-cause sequence: reproduce → instrument → isolate → test alternatives → fix → regression test.";
 l.research="Form a falsifiable question about "+concept+" within "+l.unit+", define a baseline and a disconfirming result, then report uncertainty, negative results and threats to validity.";
 l.stageSteps=st;
 l.workedExample={title:l.stage+" worked example — "+concept,text:"Use "+concept+" as the concrete object of study. "+p.c,steps:st};
 l.secondExample={title:"Failure-boundary example — "+concept,text:p.f,steps:["Freeze the baseline.","Change one relevant condition.","Predict the boundary behavior.","Measure and explain the result."]};
 l.practice=["Reconstruct the mechanism without copying the example.","Apply it to a new dataset, configuration or constraint.","Add a boundary/adversarial test.","Compare against baseline evidence.","Explain what remained invariant and what changed."];
 l.beginnerWarnings=["Do not hide assumptions behind defaults.","Do not change multiple variables when testing causality.","Do not treat one run as a stable result.","A passing demo is not proof of correctness."];
 l.lab={title:concept+" — "+l.stage+" deep lab",objective:"Build, break and measure "+concept+" under a controlled change.",steps:["Create a reproducible baseline.","Apply the stage-specific intervention.","Capture measurements and failure traces.","Explain the result and limitation."],success:"Reproducible artifact, explicit invariant and evidence-backed conclusion."};
 l.misconceptions=["API usage is not the same as understanding.","A better aggregate metric does not prove every failure mode improved.","A surprising result must be investigated before being labeled a bug.","Changing assumptions can change the valid operating regime."];
 l.checkpoint=["What is the central mechanism or invariant?","What controlled change exposes its boundary?","What evidence would convince another engineer?"];
 l.checkpointAnswers=[p.c,p.f,"A reproducible baseline comparison with explicit measurements, assumptions and limitations."];
 l.highlights=[concept+" — mechanism before optimization.","Baseline → intervention → measurement → interpretation.","Failure boundaries are part of the concept.","Reproducibility is evidence."];
 l.keyNotes=["Concept focus: "+concept+".","Define objects and assumptions before implementation.","Keep the evaluation protocol fixed while changing the intended variable.","Preserve unsuccessful runs.","Connect the lesson to the next stage."];
 l.evidence="Evidence for "+concept+" must demonstrate the mechanism, controlled implementation or derivation, measured behavior, failure analysis and limitations.";
 l.deliverable="Submit the artifact, tests, baseline comparison, failure analysis and concise technical note.";
}
globalThis.__CURRICULUM_DEPTH_AUDIT={profiles:Object.keys(P).length,enriched:LESSONS.filter(l=>l.module!=="m1").length};
})();